"""Project the experiments into the warm-tier ledger (charter #5). The ledger
is the ONLY thing a researcher loads by default; everything else is cold.

    python ledger.py --repo <investigation-dir>

Writes <repo>/LEDGER.md (human) and <repo>/ledger.jsonl (machine). Both are
projections of the EXP front-matter — never hand-edited.
"""
import argparse
import json
from pathlib import Path

import rp_common as rp

STATUS_MARK = {"registered": "○", "running": "◐", "observed": "◑",
               "reproduced": "◕", "concluded": "●"}
VERDICT_MARK = {"confirmed": "✓", "refuted": "✗", "inconclusive": "?", "": "·"}


def render(repo):
    exps = rp.load_investigation(repo)
    rows = []
    for e in exps:
        rows.append({
            "id": e["id"], "status": e["status"], "verdict": e["verdict"],
            "lens": e["lens"], "tags": e["tags"], "builds_on": e["builds_on"],
            "refines": e["refines"], "contradicts": e["contradicts"],
            "effect_vs_noise": e["effect_vs_noise"], "conclusion": e["conclusion"],
            "path": e["path"],
        })
    (Path(repo) / "ledger.jsonl").write_text(
        "".join(json.dumps(r) + "\n" for r in rows))

    lines = ["# Ledger", "",
             "Warm-tier index — one line per experiment. Generated by "
             "`research-process/orchestration/ledger.py`; do not hand-edit.", "",
             "| | id | verdict | lens | tags | builds_on | conclusion |",
             "|---|---|---|---|---|---|---|"]
    for r in rows:
        sm = STATUS_MARK.get(r["status"], "?")
        vm = VERDICT_MARK.get(r["verdict"], "·")
        tags = ", ".join(r["tags"][:3])
        deps = ", ".join(r["builds_on"]) or "—"
        concl = (r["conclusion"][:110] + "…") if len(r["conclusion"]) > 110 else r["conclusion"]
        lines.append(f"| {sm}{vm} | {r['id']} | {r['verdict'] or '—'} | {r['lens']} "
                     f"| {tags} | {deps} | {concl} |")
    n = len(rows)
    conc = sum(1 for r in rows if r["status"] == "concluded")
    lines += ["", f"*{n} experiments · {conc} concluded · "
              f"legend ○◐◑◕● status, ✓✗? verdict.*"]
    (Path(repo) / "LEDGER.md").write_text("\n".join(lines) + "\n")
    return n, conc


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    a = ap.parse_args()
    n, c = render(a.repo)
    print(f"ledger: {n} experiments ({c} concluded) → {a.repo}/LEDGER.md + ledger.jsonl")
